package app.honguyen.forge.designsystem.theme

import androidx.compose.ui.graphics.Color

/*
 * Forge Material 3 color roles, generated from the brand key colors via the HCT
 * tonal-palette algorithm (Material Color Utilities). Do not hand-edit individual
 * values — regenerate from the seeds if the palette changes.
 *
 * Seeds: primary Smaragdine #50C878 · secondary Mikado #FFC40C · tertiary Plum #8E4585
 *        neutral near-black (untinted) · error #FF5449 · live #FF1E4D
 */

// --- Light scheme ---
val primaryLight = Color(0xFF006D36)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF83FBA5)
val onPrimaryContainerLight = Color(0xFF00210C)
val secondaryLight = Color(0xFF775A00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDF9A)
val onSecondaryContainerLight = Color(0xFF251A00)
val tertiaryLight = Color(0xFF8C4383)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F4)
val onTertiaryContainerLight = Color(0xFF390036)
val errorLight = Color(0xFFB81F1E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCFCFC)
val onBackgroundLight = Color(0xFF1B1B1B)
val surfaceLight = Color(0xFFFCFCFC)
val onSurfaceLight = Color(0xFF1B1B1B)
val surfaceVariantLight = Color(0xFFE2E2E2)
val onSurfaceVariantLight = Color(0xFF474747)
val outlineLight = Color(0xFF777777)
val outlineVariantLight = Color(0xFFC6C6C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFF1F1F1)
val inversePrimaryLight = Color(0xFF66DD8B)
val surfaceDimLight = Color(0xFFDADADA)
val surfaceBrightLight = Color(0xFFF9F9F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3F3)
val surfaceContainerLight = Color(0xFFEEEEEE)
val surfaceContainerHighLight = Color(0xFFE8E8E8)
val surfaceContainerHighestLight = Color(0xFFE2E2E2)
val liveLight = Color(0xFFBE0033)
val onLiveLight = Color(0xFFFFFFFF)
val liveContainerLight = Color(0xFFFFDADA)
val onLiveContainerLight = Color(0xFF40000B)

// --- Dark scheme ---
val primaryDark = Color(0xFF66DD8B)
val onPrimaryDark = Color(0xFF003919)
val primaryContainerDark = Color(0xFF005227)
val onPrimaryContainerDark = Color(0xFF83FBA5)
val secondaryDark = Color(0xFFF8BE00)
val onSecondaryDark = Color(0xFF3F2E00)
val secondaryContainerDark = Color(0xFF5A4300)
val onSecondaryContainerDark = Color(0xFFFFDF9A)
val tertiaryDark = Color(0xFFFFABF0)
val onTertiaryDark = Color(0xFF561251)
val tertiaryContainerDark = Color(0xFF702B6A)
val onTertiaryContainerDark = Color(0xFFFFD7F4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131313)
val onBackgroundDark = Color(0xFFE2E2E2)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE2E2E2)
val surfaceVariantDark = Color(0xFF474747)
val onSurfaceVariantDark = Color(0xFFC6C6C6)
val outlineDark = Color(0xFF919191)
val outlineVariantDark = Color(0xFF474747)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E2)
val inverseOnSurfaceDark = Color(0xFF303030)
val inversePrimaryDark = Color(0xFF006D36)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF393939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1B1B1B)
val surfaceContainerDark = Color(0xFF1F1F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353535)
val liveDark = Color(0xFFFFB3B5)
val onLiveDark = Color(0xFF680018)
val liveContainerDark = Color(0xFF920025)
val onLiveContainerDark = Color(0xFFFFDADA)
